# ä¸ blowfish/i18n ç›®å½•ä¸‹çš„æ–‡ä»¶åå‰ç¼€ä¸€è‡´.
# å®˜æ–¹è‡ªå¸¦çš„ i18n/zh-CN.yaml ä¸­çš„éƒ¨åˆ†é…ç½®è¢«æ³¨é‡Šäº†, å¯¼è‡´ä¸èƒ½æ­£ç¡®æ˜¾ç¤ºæ–‡ä»¶æ›´æ–°æ—¶é—´ç­‰å†…å®¹,éœ€è¦ä¿®æ­£.
languageCode = "zh-CN" 
languageName = "cn"
weight = 1
title = "Opsnull"

[params]
displayName = "ğŸ‡¨ğŸ‡³"
isoCode = "zh-cn"
rtl = false
dateFormat = "2006-01-02" # æ˜¾ç¤ºåˆ°æ—¥æœŸå³å¯ï¼Œæ˜¾ç¤ºæ—¶é—´å¤ªé•¿
#logo = "img/opsnull_head.png" # blog é¦–é¡µå·¦ä¸Šè§’æ˜¾ç¤ºçš„ç…§ç‰‡
#secondaryLogo = "img/secondary-logo.png"
description = "æ¬¢è¿è®¿é—® opsnull çš„åšå®¢"
#copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "opsnull"
  image = "img/opsnull.jpeg" # æ”¾åˆ° assets/ ç›®å½•ä¸‹ï¼Œä¸ªäººä»‹ç»éƒ¨åˆ†æ˜¾ç¤ºã€‚
  headline = "Yet Another Hacker." # é¦–é¡µæ˜¾ç¤ºçš„ä¸ªäººä¿¡æ¯ã€‚
  bio = "Yet Another Hacker."  # æ¯ç¯‡æ–‡æ¡£æ˜¾ç¤ºçš„ä½œè€…ä¿¡æ¯
  links = [
    { email = "mailto:geekard@gmail.com" },
    { github = "https://github.com/opsnull" },
    { weibo = "https://weibo.com/u/13333" },
    { twitter = "https://twitter.com/geekard_zj" },
  ]
